import { useEffect, useState } from 'react'
import { Save, X } from 'lucide-react'
import type { TipoProducto, TipoProductoFormData } from '../../types/tipoProducto'
interface Props { abierto: boolean; tipoProducto: TipoProducto | null; error: string; soloLectura?: boolean; onClose: () => void; onSubmit: (datos: TipoProductoFormData) => void }
export function TipoProductoFormModal({ abierto, tipoProducto, error, soloLectura = false, onClose, onSubmit }: Props) {
  const [form, setForm] = useState<TipoProductoFormData>({ nombre: '', descripcion: '' }); const [errores, setErrores] = useState({ nombre: '', descripcion: '' })
  useEffect(() => { if (abierto) { setForm(tipoProducto ? { nombre: tipoProducto.nombre, descripcion: tipoProducto.descripcion } : { nombre: '', descripcion: '' }); setErrores({ nombre: '', descripcion: '' }) } }, [abierto, tipoProducto])
  if (!abierto) return null
  const cambiar = (campo: keyof TipoProductoFormData, valor: string) => { setForm((actual) => ({ ...actual, [campo]: valor })); setErrores((actual) => ({ ...actual, [campo]: '' })) }
  const validar = () => { const e = { nombre: '', descripcion: '' }; const n = form.nombre.trim(); const d = form.descripcion.trim(); if (!n) e.nombre = 'Campo requerido'; else if (n.length < 2) e.nombre = 'Debe tener al menos 2 caracteres'; if (!d) e.descripcion = 'Campo requerido'; setErrores(e); return !e.nombre && !e.descripcion }
  return <div className="maestro-modal-backdrop" role="presentation"><div className="maestro-modal-card" role="dialog" aria-modal="true" aria-labelledby="tipo-producto-form-title"><div className="maestro-modal-header"><div className="maestro-modal-header__content"><h3 id="tipo-producto-form-title" className="maestro-modal-title">{soloLectura ? 'Visualizar tipo de producto' : tipoProducto ? 'Editar tipo de producto' : 'Registrar tipo de producto'}</h3></div><button type="button" className="btn maestro-modal-close" onClick={onClose} aria-label="Cerrar modal"><X size={18} /></button></div><form noValidate onSubmit={(event) => { event.preventDefault(); if (!soloLectura && validar()) onSubmit({ nombre: form.nombre.trim(), descripcion: form.descripcion.trim() }) }}><div className="maestro-modal-body">{error && <div className="alert alert-danger py-2" role="alert">{error}</div>}<div className="mb-3"><label className="form-label required" htmlFor="tipoProductoNombreModal">Nombre de tipo de producto</label><input id="tipoProductoNombreModal" className={`form-control${errores.nombre ? ' maestro-control--error' : ''}`} value={form.nombre} placeholder="Ingresar" disabled={soloLectura} maxLength={80} onChange={(e) => cambiar('nombre', e.target.value)} />{errores.nombre && <div className="maestro-field-error">{errores.nombre}</div>}</div><div><label className="form-label required" htmlFor="tipoProductoDescripcionModal">Descripción</label><textarea id="tipoProductoDescripcionModal" className={`form-control${errores.descripcion ? ' maestro-control--error' : ''}`} value={form.descripcion} placeholder="Ingresar" disabled={soloLectura} maxLength={250} rows={2} onChange={(e) => cambiar('descripcion', e.target.value)} /><div className="d-flex justify-content-between"><div>{errores.descripcion && <span className="maestro-field-error">{errores.descripcion}</span>}</div><small className="text-muted">{form.descripcion.length}/250</small></div></div></div>{!soloLectura && <div className="maestro-modal-footer"><button type="button" className="btn maestro-btn-danger" onClick={onClose}><X size={18} />Cancelar</button><button type="submit" className="btn maestro-btn-primary"><Save size={18} />{tipoProducto ? 'Guardar cambios' : 'Registrar'}</button></div>}</form></div></div>
}

