import type { TipoDocumento, TipoDocumentoFormData } from '../types/tipoDocumento'
import { registrarEventoBitacora } from './bitacoraService'
const STORAGE_KEY = 'agrihusac_tipos_documento'
type RegistroGuardado = Partial<TipoDocumento> & { id?: number | string; estado?: boolean }
function normalizarRegistro(r: RegistroGuardado): TipoDocumento | null { const id = typeof r.id === 'number' ? r.id : Number(String(r.id ?? '').replace(/^TD-/, '')); if (!Number.isInteger(id) || id <= 0 || !String(r.nombre ?? '').trim()) return null; return { id, nombre: String(r.nombre).trim(), descripcion: String(r.descripcion ?? '').trim(), activo: r.activo === 0 || r.activo === 1 ? r.activo : r.estado === false ? 0 : 1 } }
function leer(): TipoDocumento[] { try { const datos: unknown = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? '[]'); return Array.isArray(datos) ? datos.map((item) => normalizarRegistro(item as RegistroGuardado)).filter((item): item is TipoDocumento => item !== null) : [] } catch { return [] } }
function guardar(datos: TipoDocumento[]): void { localStorage.setItem(STORAGE_KEY, JSON.stringify(datos)) }
function normalizar(valor: string): string { return valor.trim().toLowerCase() }
function validar(datos: TipoDocumentoFormData): void { const nombre = datos.nombre.trim(); const descripcion = datos.descripcion.trim(); if (!nombre) throw new Error('El nombre del tipo de documento es obligatorio.'); if (nombre.length < 2) throw new Error('El nombre debe tener al menos 2 caracteres.'); if (nombre.length > 80) throw new Error('El nombre no puede superar los 80 caracteres.'); if (!descripcion) throw new Error('La descripción es obligatoria.'); if (descripcion.length > 250) throw new Error('La descripción no puede superar los 250 caracteres.') }
export function obtenerTiposDocumento(): TipoDocumento[] { const datos = leer().sort((a, b) => a.id - b.id); guardar(datos); return datos.map((item) => ({ ...item })) }
export function crearTipoDocumento(datos: TipoDocumentoFormData): TipoDocumento { validar(datos); const lista = obtenerTiposDocumento(); if (lista.some((item) => normalizar(item.nombre) === normalizar(datos.nombre))) throw new Error('Ya existe un tipo de documento con ese nombre.'); const nuevo: TipoDocumento = { id: lista.reduce((max, item) => Math.max(max, item.id), 0) + 1, nombre: datos.nombre.trim(), descripcion: datos.descripcion.trim(), activo: 1 }; guardar([...lista, nuevo].sort((a, b) => a.id - b.id)); registrarEventoBitacora({ modulo: 'Tipos de documento', accion: 'CREAR', detalle: `Se creó el tipo de documento "${nuevo.nombre}".`, registroId: String(nuevo.id) }); return nuevo }
export function actualizarTipoDocumento(id: number, datos: TipoDocumentoFormData): TipoDocumento { validar(datos); const lista = obtenerTiposDocumento(); const actual = lista.find((item) => item.id === id); if (!actual) throw new Error('El tipo de documento no existe.'); if (actual.activo === 0) throw new Error('Un tipo de documento inactivo solo puede visualizarse o reactivarse.'); if (lista.some((item) => item.id !== id && normalizar(item.nombre) === normalizar(datos.nombre))) throw new Error('Ya existe otro tipo de documento con ese nombre.'); const actualizado = { ...actual, nombre: datos.nombre.trim(), descripcion: datos.descripcion.trim() }; guardar(lista.map((item) => item.id === id ? actualizado : item)); registrarEventoBitacora({ modulo: 'Tipos de documento', accion: 'EDITAR', detalle: `Se actualizó el tipo de documento "${actualizado.nombre}".`, registroId: String(id) }); return actualizado }
export function eliminarTipoDocumento(id: number): void { const lista = obtenerTiposDocumento(); const actual = lista.find((item) => item.id === id); if (!actual) throw new Error('El tipo de documento no existe.'); guardar(lista.map((item) => item.id === id ? { ...item, activo: 0 as const } : item)); registrarEventoBitacora({ modulo: 'Tipos de documento', accion: 'ELIMINAR', detalle: `Se desactivó el tipo de documento "${actual.nombre}".`, registroId: String(id) }) }
export function reactivarTipoDocumento(id: number): TipoDocumento { const lista = obtenerTiposDocumento(); const actual = lista.find((item) => item.id === id); if (!actual) throw new Error('El tipo de documento no existe.'); const resultado = { ...actual, activo: 1 as const }; guardar(lista.map((item) => item.id === id ? resultado : item)); registrarEventoBitacora({ modulo: 'Tipos de documento', accion: 'EDITAR', detalle: `Se reactivó el tipo de documento "${actual.nombre}".`, registroId: String(id) }); return resultado }
