import type { UnidadMedida, UnidadMedidaFormData } from '../types/unidadMedida'
import { registrarEventoBitacora } from './bitacoraService'
const STORAGE_KEY = 'agrihusac_unidades_medida'
const UNIDADES_INICIALES: UnidadMedida[] = [
  { id: 1, nombre: 'Unidad', descripcion: 'Unidad individual de un producto.', activo: 1, fechaRegistro: '10/08/2026' },
  { id: 2, nombre: 'Kilogramo', descripcion: 'Unidad de masa equivalente a mil gramos.', activo: 1, fechaRegistro: '11/08/2026' },
  { id: 3, nombre: 'Litro', descripcion: 'Unidad utilizada para medir volumen.', activo: 1, fechaRegistro: '12/08/2026' },
  { id: 4, nombre: 'Metro', descripcion: 'Unidad utilizada para medir longitud.', activo: 1, fechaRegistro: '13/08/2026' },
  { id: 5, nombre: 'Caja', descripcion: 'Embalaje que contiene varias unidades.', activo: 1, fechaRegistro: '14/08/2026' },
]
type RegistroGuardado = Partial<UnidadMedida> & { id?: number | string; estado?: boolean }
function normalizarRegistro(r: RegistroGuardado): UnidadMedida | null { const id = typeof r.id === 'number' ? r.id : Number(String(r.id ?? '').replace(/^UM-/, '')); if (!Number.isInteger(id) || id <= 0 || !String(r.nombre ?? '').trim()) return null; return { id, nombre: String(r.nombre).trim(), descripcion: String(r.descripcion ?? '').trim(), activo: r.activo === 0 || r.activo === 1 ? r.activo : r.estado === false ? 0 : 1 } }
function leer(): UnidadMedida[] { try { const datos: unknown = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? '[]'); return Array.isArray(datos) ? datos.map((item) => normalizarRegistro(item as RegistroGuardado)).filter((item): item is UnidadMedida => item !== null) : [] } catch { return [] } }
function guardar(datos: UnidadMedida[]): void { localStorage.setItem(STORAGE_KEY, JSON.stringify(datos)) }
function normalizar(valor: string): string { return valor.trim().toLowerCase() }
function validar(datos: UnidadMedidaFormData): void { const n = datos.nombre.trim(); const d = datos.descripcion.trim(); if (!n) throw new Error('El nombre de la unidad de medida es obligatorio.'); if (n.length < 2) throw new Error('El nombre debe tener al menos 2 caracteres.'); if (n.length > 60) throw new Error('El nombre no puede superar los 60 caracteres.'); if (!d) throw new Error('La descripción es obligatoria.'); if (d.length > 200) throw new Error('La descripción no puede superar los 200 caracteres.') }
export function obtenerUnidadesMedida(): UnidadMedida[] { const guardadas = leer(); const datos = (guardadas.length ? guardadas : UNIDADES_INICIALES.map((item) => ({ ...item }))).sort((a, b) => a.id - b.id); guardar(datos); return datos.map((item) => ({ ...item })) }
export function crearUnidadMedida(datos: UnidadMedidaFormData): UnidadMedida { validar(datos); const lista = obtenerUnidadesMedida(); if (lista.some((item) => normalizar(item.nombre) === normalizar(datos.nombre))) throw new Error('Ya existe una unidad de medida con ese nombre.'); const nueva: UnidadMedida = { id: lista.reduce((max, item) => Math.max(max, item.id), 0) + 1, nombre: datos.nombre.trim(), descripcion: datos.descripcion.trim(), activo: 1 }; guardar([...lista, nueva].sort((a, b) => a.id - b.id)); registrarEventoBitacora({ modulo: 'Unidades de medida', accion: 'CREAR', detalle: `Se creó la unidad de medida "${nueva.nombre}".`, registroId: String(nueva.id) }); return nueva }
export function actualizarUnidadMedida(id: number, datos: UnidadMedidaFormData): UnidadMedida { validar(datos); const lista = obtenerUnidadesMedida(); const actual = lista.find((item) => item.id === id); if (!actual) throw new Error('La unidad de medida no existe.'); if (actual.activo === 0) throw new Error('Una unidad inactiva solo puede visualizarse o reactivarse.'); if (lista.some((item) => item.id !== id && normalizar(item.nombre) === normalizar(datos.nombre))) throw new Error('Ya existe otra unidad de medida con ese nombre.'); const actualizada = { ...actual, nombre: datos.nombre.trim(), descripcion: datos.descripcion.trim() }; guardar(lista.map((item) => item.id === id ? actualizada : item)); registrarEventoBitacora({ modulo: 'Unidades de medida', accion: 'EDITAR', detalle: `Se actualizó la unidad de medida "${actualizada.nombre}".`, registroId: String(id) }); return actualizada }
export function eliminarUnidadMedida(id: number): void { const lista = obtenerUnidadesMedida(); const actual = lista.find((item) => item.id === id); if (!actual) throw new Error('La unidad de medida no existe.'); guardar(lista.map((item) => item.id === id ? { ...item, activo: 0 as const } : item)); registrarEventoBitacora({ modulo: 'Unidades de medida', accion: 'ELIMINAR', detalle: `Se desactivó la unidad de medida "${actual.nombre}".`, registroId: String(id) }) }
export function reactivarUnidadMedida(id: number): UnidadMedida { const lista = obtenerUnidadesMedida(); const actual = lista.find((item) => item.id === id); if (!actual) throw new Error('La unidad de medida no existe.'); const resultado = { ...actual, activo: 1 as const }; guardar(lista.map((item) => item.id === id ? resultado : item)); registrarEventoBitacora({ modulo: 'Unidades de medida', accion: 'EDITAR', detalle: `Se reactivó la unidad de medida "${actual.nombre}".`, registroId: String(id) }); return resultado }
