import { Placeholder } from '../../constants/placeholders'
import { Filter, RotateCcw, Search } from 'lucide-react'
import Select from 'react-select'
import { crearEstilosSelect } from '../../styles/reactSelectStyles'
export interface OpcionFiltroProducto { id: string | number; nombre: string }
export interface FiltrosProductosValores { busqueda: string; tipoProductoId: string; categoriaId: string; nivelStock: string; estado: string }
interface Props { valores: FiltrosProductosValores; tiposProducto: OpcionFiltroProducto[]; categorias: OpcionFiltroProducto[]; onChange: (campo: keyof FiltrosProductosValores, valor: string) => void; onBuscar: () => void; onLimpiar: () => void }
const selectStyles = crearEstilosSelect({ zIndex: 20 })
function opciones(lista: OpcionFiltroProducto[]) { return lista.map((item) => ({ value: String(item.id), label: item.nombre })) }
export function FiltrosProductos({ valores, tiposProducto, categorias, onChange, onBuscar, onLimpiar }: Props) { const tipos = opciones(tiposProducto); const cats = opciones(categorias); const stock = [{ value: 'bajo', label: 'Stock bajo' }, { value: 'normal', label: 'Stock normal' }]; const estados = [{ value: 'activo', label: 'Activo' }, { value: 'inactivo', label: 'Inactivo' }]; const renderSelect = (id: string, options: { value: string; label: string }[], value: string, campo: keyof FiltrosProductosValores) => <Select inputId={id} classNamePrefix="maestro-select" options={options} value={options.find((o) => o.value === value) ?? null} onChange={(option) => onChange(campo, option?.value ?? '')} placeholder={Placeholder.Seleccionar} isClearable isSearchable={false} menuPortalTarget={document.body} styles={selectStyles} />; return <section className="maestro-filter-card card border-0 shadow-sm"><div className="card-body p-3"><div className="mb-3"><span className="maestro-kicker"><Filter size={16} />Filtros de búsqueda</span></div><form className="row g-3" onSubmit={(e) => { e.preventDefault(); onBuscar() }}><div className="col-12 col-md-6"><label className="form-label" htmlFor="buscarProducto">Código o nombre</label><input id="buscarProducto" className="form-control" value={valores.busqueda} placeholder={Placeholder.Buscar} onChange={(e) => onChange('busqueda', e.target.value)} /></div><div className="col-12 col-md-3"><label className="form-label" htmlFor="filtroTipoProducto">Tipo</label>{renderSelect('filtroTipoProducto', tipos, valores.tipoProductoId, 'tipoProductoId')}</div><div className="col-12 col-md-3"><label className="form-label" htmlFor="filtroCategoriaProducto">Categoría</label>{renderSelect('filtroCategoriaProducto', cats, valores.categoriaId, 'categoriaId')}</div><div className="col-12 col-md-3"><label className="form-label" htmlFor="filtroStockProducto">Nivel de stock</label>{renderSelect('filtroStockProducto', stock, valores.nivelStock, 'nivelStock')}</div><div className="col-12 col-md-3"><label className="form-label" htmlFor="filtroEstadoProducto">Estado</label>{renderSelect('filtroEstadoProducto', estados, valores.estado, 'estado')}</div><div className="col-12"><div className="maestro-filter-actions"><button type="button" className="btn btn-maestro-secondary" onClick={onLimpiar}><RotateCcw size={18} />Limpiar</button><button type="submit" className="btn btn-maestro-primary"><Search size={18} />Buscar</button></div></div></form></div></section> }
