import { Filter, RotateCcw, Search } from 'lucide-react'
import Select from 'react-select'
export interface OpcionFiltroProducto { id: string | number; nombre: string }
export interface FiltrosProductosValores { busqueda: string; tipoProductoId: string; categoriaId: string; nivelStock: string; estado: string }
interface Props { valores: FiltrosProductosValores; tiposProducto: OpcionFiltroProducto[]; categorias: OpcionFiltroProducto[]; onChange: (campo: keyof FiltrosProductosValores, valor: string) => void; onBuscar: () => void; onLimpiar: () => void }
const selectStyles = { control: (p: any, s: any) => ({ ...p, minHeight: '36px', height: '36px', borderRadius: '8px', border: '1px solid rgb(17 24 39 / 10%)', borderColor: s.isFocused ? 'rgb(51 143 60 / 55%)' : 'rgb(17 24 39 / 10%)', backgroundColor: s.isFocused ? '#fff' : '#f9fbfa', boxShadow: s.isFocused ? '0 0 0 0.22rem rgb(51 143 60 / 12%)' : 'none', '&:hover': { borderColor: s.isFocused ? 'rgb(51 143 60 / 55%)' : 'rgb(17 24 39 / 10%)' } }), valueContainer: (p: any) => ({ ...p, padding: '0 12px', fontSize: '0.8rem' }), singleValue: (p: any) => ({ ...p, color: '#344054', fontSize: '0.8rem' }), placeholder: (p: any) => ({ ...p, color: '#667085', fontSize: '0.8rem' }), indicatorsContainer: (p: any) => ({ ...p, height: '34px' }), menu: (p: any) => ({ ...p, zIndex: 20 }), option: (p: any, s: any) => ({ ...p, fontSize: '0.8rem', backgroundColor: s.isSelected ? '#e9f8ee' : s.isFocused ? '#f3faf5' : '#fff', color: '#344054' }) }
function opciones(lista: OpcionFiltroProducto[]) { return lista.map((item) => ({ value: String(item.id), label: item.nombre })) }
export function FiltrosProductos({ valores, tiposProducto, categorias, onChange, onBuscar, onLimpiar }: Props) { const tipos = opciones(tiposProducto); const cats = opciones(categorias); const stock = [{ value: 'bajo', label: 'Stock bajo' }, { value: 'normal', label: 'Stock normal' }]; const estados = [{ value: 'activo', label: 'Activo' }, { value: 'inactivo', label: 'Inactivo' }]; const renderSelect = (id: string, options: { value: string; label: string }[], value: string, campo: keyof FiltrosProductosValores) => <Select inputId={id} options={options} value={options.find((o) => o.value === value) ?? null} onChange={(option) => onChange(campo, option?.value ?? '')} placeholder="Seleccionar" isClearable isSearchable={false} styles={selectStyles} />; return <section className="maestro-filter-card card border-0 shadow-sm"><div className="card-body p-3"><div className="mb-3"><span className="maestro-kicker"><Filter size={16} />Filtros de productos</span></div><form className="row g-3" onSubmit={(e) => { e.preventDefault(); onBuscar() }}><div className="col-12 col-md-6"><label className="form-label maestro-label" htmlFor="buscarProducto">Código o nombre</label><input id="buscarProducto" className="form-control" value={valores.busqueda} placeholder="Buscar" onChange={(e) => onChange('busqueda', e.target.value)} /></div><div className="col-12 col-md-3"><label className="form-label maestro-label" htmlFor="filtroTipoProducto">Tipo</label>{renderSelect('filtroTipoProducto', tipos, valores.tipoProductoId, 'tipoProductoId')}</div><div className="col-12 col-md-3"><label className="form-label maestro-label" htmlFor="filtroCategoriaProducto">Categoría</label>{renderSelect('filtroCategoriaProducto', cats, valores.categoriaId, 'categoriaId')}</div><div className="col-12 col-md-3"><label className="form-label maestro-label" htmlFor="filtroStockProducto">Nivel de stock</label>{renderSelect('filtroStockProducto', stock, valores.nivelStock, 'nivelStock')}</div><div className="col-12 col-md-3"><label className="form-label maestro-label" htmlFor="filtroEstadoProducto">Estado</label>{renderSelect('filtroEstadoProducto', estados, valores.estado, 'estado')}</div><div className="col-12"><div className="maestro-filter-actions"><button type="button" className="btn maestro-btn-secondary maestro-filter-btn" onClick={onLimpiar}><RotateCcw size={18} />Limpiar</button><button type="submit" className="btn maestro-btn-primary maestro-filter-btn"><Search size={18} />Buscar</button></div></div></form></div></section> }


