import { Boxes, Eye, Pencil, Plus, RotateCcw, Trash2, TriangleAlert } from 'lucide-react'
import { EmptyState } from '../common/EmptyState'
import type { Producto } from '../../types/producto'
import { TablePagination } from '../ui/TablePagination'
export interface ProductoFila extends Producto { tipoProductoNombre: string; categoriaNombre: string; unidadMedidaNombre: string; proveedorNombre: string }
interface Props { productos: ProductoFila[]; totalItems: number; page: number; pageSize: number; onAgregar: () => void; onEditar: (producto: Producto) => void; onVisualizar: (producto: Producto) => void; onEliminar: (producto: Producto) => void; onPageChange: (page: number) => void; onPageSizeChange: (size: number) => void }
function numeroProducto(id: string | number): number { const numero = Number(String(id).replace(/^PROD-/, '')); return Number.isFinite(numero) ? numero : 0 }
function moneda(valor: number) { return new Intl.NumberFormat('es-PE', { style: 'currency', currency: 'PEN' }).format(valor) }
export function TablaProductos({ productos, totalItems, page, pageSize, onAgregar, onEditar, onVisualizar, onEliminar, onPageChange, onPageSizeChange }: Props) { return <section className="table-card card border-0 shadow-sm"><div className="card-body p-0"><div className="table-header"><span className="maestro-kicker"><Boxes size={16} />Listado de productos</span><button type="button" className="btn table-toolbar-btn" onClick={onAgregar}><Plus size={18} />Agregar producto</button></div><div className="table-responsive"><table className="table standard-table align-middle mb-0"><thead><tr><th>N°</th><th>Código</th><th>Producto</th><th>Stock</th><th>Precio</th><th>Estado</th><th className="text-center">Acciones</th></tr></thead><tbody>{productos.length ? productos.map((producto) => { const bajo = producto.stockActual <= producto.stockMinimo; return <tr key={producto.id}><td><span className="table-id-chip">{numeroProducto(producto.id)}</span></td><td><span className="table-id-chip">{producto.codigo}</span></td><td><div className="table-cell-main"><span className="table-cell-icon"><Boxes size={16} /></span><strong>{producto.nombre}</strong></div></td><td><div className={bajo ? 'text-danger fw-semibold' : 'text-success fw-semibold'}>{bajo && <TriangleAlert size={15} className="me-1" />}{producto.stockActual} {producto.unidadMedidaNombre}</div><small className="text-muted">Mínimo: {producto.stockMinimo}</small></td><td>{moneda(producto.precioUnitario)}</td><td><span className={producto.estado ? 'status-label status-label--active' : 'status-label status-label--inactive'}><span className="status-label__dot" aria-hidden="true" />{producto.estado ? 'Activo' : 'Inactivo'}</span></td><td><div className="table-actions"><button type="button" className="btn table-action-btn" title="Visualizar" onClick={() => onVisualizar(producto)}><Eye size={16} /></button>{producto.estado ? <><button type="button" className="btn table-action-btn" title="Editar" onClick={() => onEditar(producto)}><Pencil size={16} /></button><button type="button" className="btn table-action-btn table-action-btn--danger" title="Desactivar" onClick={() => onEliminar(producto)}><Trash2 size={16} /></button></> : <button type="button" className="btn table-action-btn" title="Reactivar"><RotateCcw size={16} /></button>}</div></td></tr> }) : <tr><td colSpan={7}><EmptyState icon={Boxes} iconSize={28} title="No se encontraron productos" description="Ajusta los filtros o registra un producto." /></td></tr>}</tbody></table></div><TablePagination totalItems={totalItems} page={page} pageSize={pageSize} onPageChange={onPageChange} onPageSizeChange={onPageSizeChange} /></div></section> }
